from typing import Any, Optional, List
from PySide6.QtWebEngineWidgets import QWebEngineView

class V8Engine(QWebEngineView):
    def __init__(
        self,
        url: str = "",
        show: bool = False,
        stealth: bool = True,
        user_agent: Optional[str] = None,
        proxy: Optional[str] = None
    ) -> None: ...
    
    def wait_ready(self, timeout: int = 30000) -> bool: ...
    def load_url(self, url: str, wait: bool = True) -> bool: ...
    def run_js(self, code: str, timeout: int = 10000) -> Any: ...
    def run_js_file(self, filepath: str, timeout: int = 10000) -> Any: ...
    def hook(self, func_path: str, handler: str) -> Any: ...
    def get_local_storage(self, key: Optional[str] = None) -> Any: ...
    def set_local_storage(self, key: str, value: str) -> None: ...
    def get_console_logs(self) -> list: ...
    def get_console_errors(self) -> list: ...
    def clear_console(self) -> None: ...
    def load_html(self, html: str, base_url: str = "http://localhost/") -> bool: ...
    def inject_js(self, code: str, run_at: str = "document_end") -> None: ...
    def get_cookies(self) -> list: ...
    def set_cookie(self, name: str, value: str, domain: str = "", path: str = "/", **kwargs: Any) -> None: ...
    def screenshot(self, path: str) -> None: ...
    def open_devtools(self) -> None: ...
